---
# Copyright (C) 2016-2019 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2016-2019 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Restart slapd
  service:
    name: 'slapd'
    state: 'restarted'
