---
# Copyright (C) 2019 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2019 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

dependencies: []

galaxy_info:

  author: 'Maciej Delmanowski'
  description: 'Install WP-CLI framework'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '2.7.0'

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
    - name: GenericLinux
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - wordpress
    - wpcli
    - php
