---
# Copyright (C) 2016 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2016 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

dependencies: []

galaxy_info:

  author: 'Maciej Delmanowski'
  description: 'Manage system environment variables'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '2.0.0'
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  galaxy_tags:
  - system
  - environment
  - variables
