---
# Copyright (C) 2019 Leonardo Bechea <leonardo.bechea@innobyte.com>
# Copyright (C) 2019 Alin Alexandru <alin.alexandru@innobyte.com>
# Copyright (C) 2019 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

dependencies: []

galaxy_info:

  author: 'Bechea Leonardo, Alin Alexandru'
  description: 'Install and manage Tinyproxy service'
  company: 'DebOps'
  license: 'GPL-3.0-only'
  min_ansible_version: '1.2'
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - precise
        - xenial
        - bionic
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster
        - bullseye
  galaxy_tags:
    - tinyproxy
