---
# Copyright (C) 2017 Robin Schneider <ypid@riseup.net>
# Copyright (C) 2017 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

dependencies: []

galaxy_info:

  company: 'DebOps'
  author: 'Robin Schneider'
  description: 'Setup and manage Home Assistant'
  license: 'GPL-3.0-only'
  min_ansible_version: '2.2.2'

  platforms:

    - name: Debian
      versions:
        - jessie
        - stretch

  galaxy_tags:
    - automation
    - home
    - homeassistant
    - iot
