---

dependencies: []

galaxy_info:

  role_name: 'influxdb'
  author: 'Pedro Luis López'
  description: 'Install and manage InfluxDB client'
  company: 'Neuromobile Marketing'
  license: 'GNU General Public License v3'
  min_ansible_version: '2.9.0'
  platforms:
    - name: Debian
      versions:
        - stretch
        - buster
  galaxy_tags:
    - clustering
    - database
    - nosql
    - search
    - monitoring
    - influxdb
