---
# Copyright (C) 2020 Pedro Luis Lopez <pedroluis.lopezsanchez@gmail.com>
# Copyright (C) 2020 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: restart prometheus exporters
  service:
    name: 'prometheus-{{ item }}-exporter'
    state: 'restarted'
  with_items:
    - '{{ prometheus_exporter__combined_exporters }}'
    - '{{ prometheus_exporter__combined_go_exporters | map(attribute="name") | list }}'
