---
# Copyright (C) 2019 Leonardo Bechea <leonardo.bechea@innobyte.com>
# Copyright (C) 2019 Alin Alexandru <alin.alexandru@innobyte.com>
# Copyright (C) 2019 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

dependencies: []

galaxy_info:

  role_name: 'grafana'
  author: 'Bechea Leonardo, Alin Alexandru'
  description: 'Install and manage Grafana Dashboard'
  company: 'DebOps'
  license: 'GPL-3.0-only'
  min_ansible_version: '2.6'
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - utopic
        - vivid
        - bionic
    - name: Debian
      versions:
        - jessie
        - wheezy
        - bullseye
        - buster
  galaxy_tags:
    - grafana
