---

- name: Drop assets if requested
  sensu_asset:
    auth:
      url: '{{ sensu_server__api_url }}'
      password: '{{ sensu_server__admin_account_password }}'
    name: '{{ item.name }}'
    state: 'absent'
  with_items: '{{ sensu_server__assets|d([]) }}'
  when: (item.name|d(False) and (item.state is defined and item.state == 'absent'))

- name: Create assets
  sensu_asset:
    auth:
      url: '{{ sensu_server__api_url }}'
      password: '{{ sensu_server__admin_account_password }}'
    name: '{{ item.name }}'
    state: 'present'
    builds: '{{ item.builds | d([]) }}'
    namespace: '{{ item.namespace | d("default") }}'
    labels: '{{ item.labels | d({}) }}'
    annotations: '{{ item.annotations | d({}) }}'
  with_items: '{{ sensu_server__assets|d([]) }}'
  when: (item.name|d(False) and (item.state is undefined or item.state != 'absent'))

- name: Drop filters if requested
  sensu_filter:
    auth:
      url: '{{ sensu_server__api_url }}'
      password: '{{ sensu_server__admin_account_password }}'
    name: '{{ item.name }}'
    state: 'absent'
  with_items: '{{ sensu_server__filters|d([]) }}'
  when: (item.name|d(False) and (item.state is defined and item.state == 'absent'))

- name: Create filters
  sensu_filter:
    auth:
      url: '{{ sensu_server__api_url }}'
      password: '{{ sensu_server__admin_account_password }}'
    name: '{{ item.name }}'
    state: 'present'
    action: '{{ item.action }}'
    expressions: '{{ item.expressions | d([]) }}'
    runtime_assets: '{{ item.runtime_assets | d([]) }}'
    namespace: '{{ item.namespace | d("default") }}'
    labels: '{{ item.labels | d({}) }}'
    annotations: '{{ item.annotations | d({}) }}'
  with_items: '{{ sensu_server__filters|d([]) }}'
  when: (item.name|d(False) and (item.state is undefined or item.state != 'absent'))

- name: Drop pipe handlers if requested
  sensu_pipe_handler:
    auth:
      url: '{{ sensu_server__api_url }}'
      password: '{{ sensu_server__admin_account_password }}'
    name: '{{ item.name }}'
    state: 'absent'
  with_items: '{{ sensu_server__pipe_handlers|d([]) }}'
  when: (item.name|d(False) and (item.state is defined and item.state == 'absent'))
  no_log: True

- name: Create pipe handlers
  sensu_pipe_handler:
    auth:
      url: '{{ sensu_server__api_url }}'
      password: '{{ sensu_server__admin_account_password }}'
    name: '{{ item.name }}'
    state: 'present'
    command: '{{ item.command }}'
    filters: '{{ item.filters | d([]) }}'
    mutator: '{{ item.mutator | d() }}'
    timeout: '{{ item.timeout | d(0) }}'
    env_vars: '{{ item.env_vars | d({}) }}'
    runtime_assets: '{{ item.runtime_assets | d([]) }}'
    namespace: '{{ item.namespace | d("default") }}'
    labels: '{{ item.labels | d({}) }}'
    annotations: '{{ item.annotations | d({}) }}'
  with_items: '{{ sensu_server__pipe_handlers|d([]) }}'
  when: (item.name|d(False) and (item.state is undefined or item.state != 'absent'))
  no_log: True

- name: Drop handler sets if requested
  sensu_handler_set:
    auth:
      url: '{{ sensu_server__api_url }}'
      password: '{{ sensu_server__admin_account_password }}'
    name: '{{ item.name }}'
    state: 'absent'
  with_items: '{{ sensu_server__handler_sets|d([]) }}'
  when: (item.name|d(False) and (item.state is defined and item.state == 'absent'))

- name: Create handler sets
  sensu_handler_set:
    auth:
      url: '{{ sensu_server__api_url }}'
      password: '{{ sensu_server__admin_account_password }}'
    name: '{{ item.name }}'
    state: 'present'
    handlers: '{{ item.handlers | d([]) }}'
    namespace: '{{ item.namespace | d("default") }}'
    labels: '{{ item.labels | d({}) }}'
    annotations: '{{ item.annotations | d({}) }}'
  with_items: '{{ sensu_server__handler_sets|d([]) }}'
  when: (item.name|d(False) and (item.state is undefined or item.state != 'absent'))
