---
# Copyright (C) 2015-2017 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015-2017 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Reload systemd units
  systemd:
    daemon_reload: True
  when: ansible_local|d() and ansible_local.init|d() and
        ansible_local.init in [ 'systemd' ]

- name: Restart atd
  service:
    name: 'atd'
    state: 'restarted'
