---
# Copyright (C) 2015-2019 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015-2019 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

dependencies: []

galaxy_info:

  author: 'Maciej Delmanowski'
  description: 'Configure RStudio Server, an Integrated Development Environment for R'
  company: 'DebOps'
  license: 'GPL-3.0-only'
  min_ansible_version: '2.3.0'
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
    - name: Debian
      versions:
        - jessie
        - stretch
  galaxy_tags:
    - rlang
    - rstudio
    - ide
    - web
    - programming
    - development
    - statistics
