---
# Copyright (C) 2015-2016 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015-2016 Robin Schneider <ypid@riseup.net>
# Copyright (C) 2015-2016 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

dependencies: []

galaxy_info:

  company: 'DebOps'
  author: 'Maciej Delmanowski, Robin Schneider'
  description: 'Manage local or remote libvirt instance'
  license: 'GNU General Public License v3'
  min_ansible_version: '2.2.0'

  platforms:

    - name: Ubuntu
      versions:
        - trusty

    - name: Debian
      versions:
        - wheezy
        - jessie

  galaxy_tags:
    - system
    - virtualization
