---

- name: Manage InfluxDB server
  hosts: [ 'debops_service_influxdb_server' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: keyring
      tags: [ 'role::keyring', 'skip::keyring', 'role::nginx', 'role::influxdb_server' ]
      keyring__dependent_apt_keys:
        - '{{ influxdb_server__keyring__dependent_apt_keys }}'

    - role: ferm
      tags: [ 'role::ferm', 'skip::ferm' ]
      ferm__dependent_rules:
        - '{{ influxdb_server__ferm__dependent_rules }}'

    - role: python
      tags: [ 'role::python', 'skip::python', 'role::influxdb_server' ]
      python__dependent_packages3:
        - '{{ influxdb_server__python__dependent_packages3 }}'
      python__dependent_packages2:
        - '{{ influxdb_server__python__dependent_packages2 }}'

    - role: influxdb_server
      tags: [ 'role::influxdb_server', 'skip::influxdb_server' ]