---
# Copyright (C) 2016 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2016 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

dependencies: []

galaxy_info:

  company: 'DebOps'
  author: 'Maciej Delmanowski'
  description: 'Manage Gunicorn Debian service'
  license: 'GPL-3.0-only'
  min_ansible_version: '2.0.0'

  platforms:

    - name: Debian
      versions:
        - wheezy
        - jessie

    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty

  galaxy_tags:
    - webserver
    - python
    - django
    - wsgi
