---
# Copyright (C) 2017 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2017 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

dependencies: []

galaxy_info:

  author: 'Maciej Delmanowski'
  description: 'Install and configure OpenDKIM service'
  company: 'DebOps'
  license: 'GPL-3.0-only'
  min_ansible_version: '2.3.0'

  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
    - name: Debian
      versions:
        - jessie
        - stretch

  galaxy_tags:
    - smtp
    - milter
    - dkim
    - spf
    - dmarc
    - mail
    - security
    - antispam
