---
# Copyright (C) 2015-2017 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015-2017 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Ensure that a SQL database is available
  assert:
    that:
      - 'gitlab__database == "postgresql"'
  tags: [ 'role::gitlab:env', 'role::gitlab:assert' ]
