---
# Copyright (C) 2016 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2016 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Restart nullmailer
  service:
    name: 'nullmailer'
    state: 'restarted'

- name: Reload xinetd
  service:
    name: 'xinetd'
    state: 'reloaded'
