---
# Copyright (C) 2015      Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# Copyright (C) 2017-2020 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015-2020 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

dependencies: []

galaxy_info:

  author: 'Reto Gantenbein'
  description: 'Configure Dovecot IMAP/POP3 service'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'
  platforms:
    - name: Debian
      versions:
        - wheezy
        - jessie
  galaxy_tags:
    - imap
    - pop3
    - sieve
    - mail
