---
# Copyright (C) 2020 Pedro Luis Lopez <pedroluis.lopezsanchez@gmail.com>
# Copyright (C) 2020 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

- import_role:
    name: 'ansible_plugins'

- name: Install Prometheus exporters packages
  package:
    name: '{{ lookup("template", "lookup/prometheus_exporter__packages.j2") }}'
    state: 'present'
  register: prometheus_exporter__register_install_status
  until: prometheus_exporter__register_install_status is succeeded

- name: Divert the original prometheus exporters configuration files
  dpkg_divert:
    path: '/etc/default/prometheus-{{ item }}-exporter'
    state: 'present'
    delete: True
  with_items: '{{ prometheus_exporter__combined_exporters }}'
  tags: [ 'role::prometheus_exporter:config' ]

- name: Configure Prometheus exporters
  template:
    src: 'etc/default/prometheus-exporter.j2'
    dest: '/etc/default/prometheus-{{ item }}-exporter'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: '{{ prometheus_exporter__combined_exporters }}'
  tags: [ 'role::prometheus_exporter:config' ]
  notify: restart prometheus exporters

- name: Configure discovery files for Prometheus server
  template:
    src: 'etc/prometheus/exporter.json.j2'
    dest: '/etc/prometheus/{{ item }}.{{ inventory_hostname }}.json'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: '{{ prometheus_exporter__combined_exporters }}'
  delegate_to: '{{ prometheus_exporter__delegate_to }}'
  when: prometheus_exporter__server is defined and prometheus_exporter__server and
        prometheus_exporter__server_file_based_discovery_service

- name: Make sure that Ansible local facts directory exists
  file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    mode: '0755'

- name: Save Prometheus server local facts
  template:
    src: 'etc/ansible/facts.d/prometheus_exporter.fact.j2'
    dest: '/etc/ansible/facts.d/prometheus_exporter.fact'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: prometheus_exporter__register_local_facts

- name: Re-read local facts if they have been modified
  action: setup
  when: prometheus_exporter__register_local_facts is change
