---
# Copyright (C) 2020 Pedro Luis Lopez <pedroluis.lopezsanchez@gmail.com>
# Copyright (C) 2020 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Check if prometheus server is installed
  environment:
    LC_MESSAGES: 'C'
  shell: set -o nounset -o pipefail -o errexit &&
         dpkg-query -W -f='${Version}\n' 'prometheus'
         | grep -v '^$'
  args:
    executable: 'bash'
  register: prometheus_exporter__register_version
  changed_when: False
  failed_when: False
  check_mode: False

- name: Override configuration if local server is detected
  set_fact:
    prometheus_exporter__server: 'localhost'
  when: (prometheus_exporter__register_version.stdout|d(False))

- name: Set dependent variables with role templates
  set_fact:
    prometheus_exporter__etc_services__dependent_list_env: '{{ prometheus_exporter__etc_services__dependent_list }}'
    prometheus_exporter__ferm__dependent_rules_env: '{{ prometheus_exporter__ferm__dependent_rules }}'
